### ISSUE TITLE
Automatic documentation upload to gh-pages branch

### ISSUE THREAD

**Issue by hugopl** [hugopl/gtk4.cr#25]
Currently, the documentation at https://hugopl.github.io/gtk4.cr/ is made "manually", I mean... every time I need to update it I do:

```
git checkout gh-pages
git rm doc
git merge WHATEVER_NEW_VERSION
make doc
git add doc
git push origin gh-pages
```
These are simple and static steps that can be automatized by a github actions that runs every time a new tag is created in the repository.

**Comment by 1player** [comment]
I had started working on this on my local fork, mostly to familiarise myself with Github Actions, but the latest Ubuntu version they provide workers for is 20.04 LTS which doesn't ship with gtk4. I've read they'll release ubuntu 22.04 LTS in preview state some time in May, so I guess this is on hold until then.

**Comment by GeopJr** [comment]
I usually use [peaceiris/actions-gh-pages](https://github.com/marketplace/actions/github-pages-action) for publishing docs since it handles a lot from checking whether anything actually changed to removing all commits from the branch so it doesn't clog cloning (and many more):

- [from gettext.cr](https://github.com/GeopJr/gettext.cr/blob/d9eb7807dea6a6a3fc2b37fe10f5ec667e42449b/.github/workflows/ci.yml#L20-L25=)
- [Action readme with all the options and example workflows](https://github.com/peaceiris/actions-gh-pages#readme=)

**Comment by 1player** [comment]
I'm working on it right now, I should have something ready soon.
