### ISSUE TITLE
GC.collect instantly crashes application

### ISSUE THREAD

**Issue by BlobCodes** [hugopl/gtk4.cr#3]
In both of these given examples, the application crashes (in one example instantly, in the other one when pressing the button):
```crystal
require "gtk4"

app = Gtk::Application.new("hello.example.com", Gio::ApplicationFlags::None)
app.activate_signal.connect do
  GLib.idle_add(GLib::Priority.new(500)) do
    # Allocate memory until the gc collects or the ram is full
    Pointer(UInt8).malloc(1)
    true
  end
  window = Gtk::ApplicationWindow.new(app)
  window.present
end
app.run(ARGV)
```

```crystal
require "gtk4"

app = Gtk::Application.new("hello.example.com", Gio::ApplicationFlags::None)
app.activate_signal.connect do
  window = Gtk::ApplicationWindow.new(app)
  button = Gtk::Button.new(label: "Crash!")
  button.clicked_signal.connect { GC.collect }
  window.child = button
  window.present
end
app.run(ARGV)
```

Using `GC.disable` in either of the two examples fixes the problem, but that's not really a good solution.
I don't know if this issue actually belongs here or in gi-crystal.

**Comment by hugopl** [comment]
GC is destroying the `window` object, since there's no reference to it when the `GC.collect` call is made after the activate signal is ran.

if you do:
`button.clicked_signal.connect { window; GC.collect }`

it wont crash when you press the button, but crashes when you close the window... and I don´t know why yet :thinking:

**Comment by hugopl** [comment]
The patch above fix the crash, but the problem is more than that.

The crash was caused because the binding generator was not increasing the reference count on constructors with `transfer none` as they do for regular methods. So the crash was fixed.

Now the issue is related with the destruction order I guess, if I compile the last example with `-ddebugmemory`, after close the window I get:

```
~Gtk::ApplicationWindow at 0x557b3d054300 - ref count: 3
~Gtk::Button at 0x557b3ce84300 - ref count: 6

(crystal-run-bug.tmp:27445): Gtk-CRITICAL **: 19:15:20.435: GtkButton 0x557b3ce84300 has a parent GtkApplicationWindow 0x557b3d054300 during dispose. Parents hold a reference, so this should not happen.
Did you call g_object_unref() instead of gtk_widget_unparent()?

(crystal-run-bug.tmp:27445): Gtk-CRITICAL **: 19:15:20.435: gtk_widget_unparent: assertion 'GTK_IS_WIDGET (widget)' failed

(crystal-run-bug.tmp:27445): Gtk-WARNING **: 19:15:20.436: Finalizing GtkApplicationWindow 0x557b3d054300, but it still has children left:

(crystal-run-bug.tmp:27445): Gtk-CRITICAL **: 19:15:20.436: gtk_widget_get_name: assertion 'GTK_IS_WIDGET (widget)' failed

(crystal-run-bug.tmp:27445): Gtk-WARNING **: 19:15:20.436:    - (null) 0x557b3ce84300
```

This one I don't know yet how to solve.
