### ISSUE TITLE
Exception: Undefined constant GLib::Bytes

### ISSUE THREAD

**Issue by BlobCodes** [hugopl/gtk4.cr#6]
Using this code:
```crystal
require "gtk4"

file = Gio::File.parse_name("/some/image/path.png")
file.load_bytes(Gio::Cancellable.new)
```

Results in this exception:
```
Showing last frame. Use --error-trace for full trace.

In lib/gtk4/src/gio-2.0/file.cr:747:55

 747 | def load_bytes(cancellable : Gio::Cancellable?) : GLib::Bytes
                                                         ^----------
Error: undefined constant GLib::Bytes
```

**Comment by hugopl** [comment]
I removed Bytes from the bindings

https://github.com/hugopl/gi-crystal/blob/master/g_lib.yml#L212

my initial thought was that you would not need it since there's a Crystal equivalent, however a lot of GTK4 API use the GFile object that have Bytes as return value of some methods.... so I think I was wrong.

**Comment by hugopl** [comment]
I'm thinking if would be possible to remove GFile from API... :thinking: , in the cases that C API requires a GFile as parameter we can do a transparent conversion from Path to GFile.

The first problem I see is if some API have a GFile parameter expecting the file to be open and another API has a GFile parameter that requires the file to be closed... and things like that.

**Comment by BlobCodes** [comment]
I don't know of any API that requires the GFile to be open.. but there are a lot of methods in GFile that could be quite useful and hard to accomplish with crystal.

For example I wouldn't know how to implement g_file_trash or g_file_mount_mountable in crystal (or how to asynchronously do basic io operations using the crystal methods)

**Comment by hugopl** [comment]
Yeah, so I think GFile and GBytes must be back.

:thinking: ... for other datatypes like `GDateTime` maybe would be useful to also not remove them but instead accept the pure-Crystal type or the G* type, i.e. a function that accept a `GDateTime` as parameter would now accept `GLib::DateTime | ::Time`.

I need to do some experiments with this to see if it works.

**Comment by hugopl** [comment]
I was taking a look on this... `Gio::File` was never removed from APIs, `GLib::Bytes` was.

By what I saw `Bytes` binding need to be handmade since it is ref-counted with its own set of functions and I don't know if GIR give enough info to generate automatic bindings for this... even if it does, `Bytes` class seems to be an exception and have not much methods, so a handmade first implementation still make sense.

**Comment by hugopl** [comment]
`Bytes` is back and working, but there are still other bugs that cause `Gio::File.parse_name` to not work yet.

**Comment by hugopl** [comment]
Despite of the missing cross project reference in the commit message of https://github.com/hugopl/gi-crystal/commit/c583d0db4c44900cdab6e3976e471a0bdd92f900 if fixed this issue :tada: 

The fix was delayed because I was thinking about to refactor the code that deal with the parameters in the generator that become a bit messy over time, however my first refactor attempt failed, so it will still messy for some more time until a find time and a design to unmessify it.

BTW, now I just remove the optional parameters, for sure this doesn't match all use cases... so I'm still thinking a way to let these functions with return values + optional out parameters to be accessible on Crystal API without affect the use case where people don't care about the optional out parameter.... :thinking:
